name: Development

on:
   push:
   pull_request:
   workflow_call:
   workflow_dispatch:

jobs:
   test:
      name: Lint and Test
      uses: uicpharm/workflows/.github/workflows/lint-and-test.yml@v1
